### ISSUE TITLE
Running tests in library project that depends on other library project fails

### ISSUE THREAD

**Issue by mpost** [kageiit/gradle-robojava-plugin#10]
We are trying run tests for a library project which in turn depends on another library project. We run into problems when trying to execute all tests via gradlew or AndroidStudio.

We have created a test project with the following build.gradle file:

<pre lang="gradle">
evaluationDependsOn(':libraryA')
ext.androidProject = 'libraryA'
apply plugin: 'com.kageiit.robojava'
</pre>

Now when running the test task or the build task for that matter we get the error, that no classes from libraryB can be found when trying to compile libraryA.

A workaround is to remove the test project from the settings file, compile, readd it to the settings and than execute the tests.

Do we have to list libraryB in the build.gradle file as well?

**Comment by kageiit** [comment]
I just fixed this in #9. Please use version 1.2.2 or higher of robojava and let me know if you still see the issue.
