### ISSUE TITLE
Gradle plugin does not work anymore in Android Studio 1.1 Beta.0

### ISSUE THREAD

**Issue by mpost** [kageiit/gradle-robojava-plugin#12]
The plugin does not works anymore in the AS 1.1 Beta.0 (build from Januar 28).

The following error is shown when trying to run any individual test:

<pre lang="java">
Error:Android Gradle Build Target: java.lang.NoClassDefFoundError: com/android/ide/common/blame/parser/PatternAwareOutputParser
</pre>

**Comment by kageiit** [comment]
No plans on fixing issues on beta builds. Please reopen if it occurs on a stable version of android studio.

**Comment by mpost** [comment]
The problems is recorded here: https://code.google.com/p/android/issues/detail?id=126013
