### ISSUE TITLE
Auto-build/refresh

### ISSUE THREAD

**Issue by wongcain** [kageiit/gradle-robojava-plugin#13]
First of all, thank you for sharing this project.  It has greatly simplified my gradle config.  I have one issue with this set-up, however, and was wondering if you had a work-around.  The problem is that since my unit tests are separated by the virtual "tdd" module, their build cycle is also decoupled from the build of the rest of the project.  This causes 2 annoyances:
1. If I need to modify or refactor a class in the main project, the change does not get immediately recognized by the unit test classes.  Instead I need to manually perform an "assemble".
2. Since the unit tests reference the compiled class files instead of the source tree, I cannot as easily step-through and set break-points when unit testing.  I've gotten around this by manually attaching the sources in the project, but this setting seems to get cleared out with each Gradle refresh.

Any ideas?

**Comment by kageiit** [comment]
See #11 

You can also place your breakpoints inside your main source **before** you start debugging and it seems to hit the breakpoint and find the source correctly.
