### ISSUE TITLE
Gradle cant sync up because of "apply plugin: 'com.kageiit.robojava'"

### ISSUE THREAD

**Issue by HDANILO** [kageiit/gradle-robojava-plugin#14]
Followed the setup suggested in the start page, created the stub TDD, with the build gradle:

evaluationDependsOn(':app')
ext.androidProject = 'app'
apply plugin: 'cobertura'
apply plugin: 'com.kageiit.robojava'

Gradle never complete the sync and throw this error:
Error:(5, 0) No signature of method: com.android.build.gradle.AppPlugin.getBootClasspath() is applicable for argument types: () values: []

As you can see, line 5 is: apply plugin: 'com.kageiit.robojava'

**Comment by HDANILO** [comment]
Checking the plugin code, seems like this happens at 

https://github.com/kageiit/gradle-robojava-plugin/blob/master/robojava-plugin/src/main/groovy/com/kageiit/robojava/RobojavaPlugin.groovy#L113

**Comment by kageiit** [comment]
This plugin is not compatible with android gradle plugin greater than 1.1.0

**Comment by HDANILO** [comment]
Seems that the problem is not that, the problem in fact is a conflict with this plugin: com.jakewharton.hugo

**Comment by HDANILO** [comment]
Confirmed, removed hugo and it worked like a charm
