### ISSUE TITLE
Escape backslash ( \ ) character on windows does not work.

### ISSUE THREAD

**Issue by ogranada** [kageiit/gradle-robojava-plugin#3]
The strings in RobojavaConfig.java file have errors on escape the \ character, see the function writeProperties in RobojavaPlugin class (Lines 160 to 172).

**Comment by kageiit** [comment]
Which version of Robojava are you using?
This has already been fixed in #2 and release in version 1.1.5.

**Comment by ogranada** [comment]
Thanks, It works. :D
