### ISSUE TITLE
Cobertura reports don't show main androidTest results...

### ISSUE THREAD

**Issue by nealsanche** [kageiit/gradle-robojava-plugin#4]
Hi! Love the plugin so far, just working with it on a test project to figure it out. I get an empty Cobertura report for classes inside the `src/androidTest/myPackage/*Test.java`, in that those classes never appear in the cobertura reports. I see that in the example project you have created, cobertura only reports on the classes in the flavor variant. I wonder if this is intended? I am not using flavors, and so my `tdd/build.gradle` looks like the following:

```
evaluationDependsOn(':app')
ext.androidProject = 'app'
apply plugin: 'cobertura' // add if you want code coverage
apply plugin: 'com.kageiit.robojava'
```

and my application's `build.gradle` file looks like the following:

```
apply plugin: 'com.android.application'

dependencies {
    androidTestCompile 'junit:junit:4.12'
    androidTestCompile('org.robolectric:robolectric:2.4') {
        exclude group: "commons-logging", module: "commons-logging"
        exclude group: "org.apache.httpcomponents", module: "httpclient"
    }
    // needed because of a bug in cobertura with the bundled version of xerces
    androidTestCompile 'xerces:xercesImpl:2.7.1'
}

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    // add generated-sources to be able to import RobojavaConfig foreasy configuration of custom testrunner
    sourceSets.androidTest.java.srcDirs += 'build/generated-sources'
}
```

Thanks for any directions or hints as to why these classes don't get reported on.

**Comment by kageiit** [comment]
Hmm, Flavor support for cobertura was not something I tested extensively. But on a project with no flavors, it should work fine.

s it possible for you to push the test project to a repository so I can see whats going on? Just a sandbox for figuring out the issue so I can incorporate fixes if any as it would help me understand the problem better.

**Comment by nealsanche** [comment]
Sure, I'll push this little test app up to Github so you can take a look.

**Comment by nealsanche** [comment]
Okay, nothing fancy, but here's the repository where I've stashed it: https://github.com/nealsanche/RoboJavaTest

Specifically, running `./gradlew cobertura` generates an empty report, which is unexpected.

**Comment by nealsanche** [comment]
Strangely, on my more detailed project, the cobertura plugin is working great, and produces a lot of output in the report.

**Comment by kageiit** [comment]
Yeah i am noticing that too. I am not too worried about it working on a trivial toy project. I used it in a lot of other projects and cobertura coverage is great to have. I will fix the example to produce correct cobertura output when I get a chance. closing this for now.
