### ISSUE TITLE
Unknown Resources

### ISSUE THREAD

**Issue by nealsanche** [kageiit/gradle-robojava-plugin#6]
I've just tried to integrate Robojava into a more detailed project, with a fair number of integrated android library dependencies, and there are errors.

![screen shot 2015-01-09 at 9 48 20 am](https://cloud.githubusercontent.com/assets/5369033/5683394/b583e36c-97e4-11e4-80be-11d738e2917a.png)

My build directory doesn't have an `intermediates/assets/development/debug` as all, as far as I can tell. Instead it looks like:

![screen shot 2015-01-09 at 9 50 41 am](https://cloud.githubusercontent.com/assets/5369033/5683426/04dde6b0-97e5-11e4-869d-b4adda0301ea.png)

The generated RobojavaConfig.java is definitely not setting the `RESOURCES` and `ASSETS` to the correct thing in this case, where there are many dependencies with resources of their own.

**Comment by nealsanche** [comment]
I'm still trying to figure out how to reproduce this on a smaller app, so unless it's something obvious, don't worry about this yet.

**Comment by nealsanche** [comment]
Alright, here's what's going on with this: I had changed my applicationId based on the flavor by using a contruct like the following:

```
    productFlavors {
        def productionSigningConfig = signingConfigs.production
        def developmentSigningConfig = signingConfigs.release
        development {
            signingConfig developmentSigningConfig
            applicationId "my.application.debug"
        }

        production {
            signingConfig productionSigningConfig
        }
    }
```

This caused confusion with the plugin. The app was being compiled with the default applicationId, and since the applicationId is overridden, it wasn't finding the resources.

But, once that was fixed, I found that the `${applicationId}` replacement in my AndroidManifest.xml was not working properly, and so another component I'm using was throwing errors about not being able to find attributes in the manifest.

So, two things need to work better: Allowing the overriding of applicationId on a flavor. And the second is following the new manifest merging logic somehow.

**Comment by kageiit** [comment]
Robojava does not configure the application ID, the Robolectric manifest does however, so you may override it like this:

```java
package com.kageiit.test;

import org.robolectric.AndroidManifest;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;
import org.robolectric.res.Fs;

import static com.kageiit.robojava.RobojavaConfig.ASSETS;
import static com.kageiit.robojava.RobojavaConfig.MANIFEST;
import static com.kageiit.robojava.RobojavaConfig.RESOURCES;

/**
 * Custom test runner which is needed if your tests need resources etc.
 */
public class RobojavaTestRunner extends RobolectricTestRunner {

    private static final int TARGET_SDK_VERSION = 18;
    private static final AndroidManifest ANDROID_MANIFEST = getAndroidManifest();

    public RobojavaTestRunner(final Class<?> testClass) throws Exception {
        super(testClass);
    }

    @Override
    public AndroidManifest getAppManifest(Config config) {
        return ANDROID_MANIFEST;
    }

    private static AndroidManifest getAndroidManifest() {
        return new AndroidManifest(Fs.fileFromPath(MANIFEST),
                Fs.fileFromPath(RESOURCES),
                Fs.fileFromPath(ASSETS)) {
            @Override
            public int getTargetSdkVersion() {
                return TARGET_SDK_VERSION;
            }
            
            @Override
            public String getApplicationName(){
                return "TestApplicationName";
            } 
        };
    }
}
```

**Comment by nealsanche** [comment]
Yeah, I found I was also able to work around this by creating a new productFlavor that uses just the default applicationId too. So there's definitely a couple of workarounds that work here. Thanks.
