### ISSUE TITLE
Allow to provide vm parameters to vm executing the tests

### ISSUE THREAD

**Issue by mpost** [kageiit/gradle-robojava-plugin#7]
We have a lot of robolectric tests that we currently execute with the robolectric gradle plugin. We are looking at this plugin for better integration with AS but are missing the ability to configure the vm instance running the test. Especially memory details. In robolectric we applied:

<pre lang="groovy">
robolectric {
    include '**/*_Test.class'
    maxHeapSize = '2048m'
    maxParallelForks = 4
    forkEvery = 200
    jvmArgs '-XX:MaxPermSize=512m', '-XX:-UseSplitVerifier'
    ignoreFailures false
}
</pre>

The most important option for us is the maxHeap and maxPerm. Is it possible to set those params? Currently the process stales with OutOfMemoryExceptions when using gradle-robojava-plugin.

**Comment by kageiit** [comment]
Robojava plugin already applies the java plugin on the test stub project. to it is trivial to configure it and has more options that the robolectric gradle plugin. (The robolectric gradle plugin, wraps them and has to update it's extension whenever the test dsl changes or new ones have to be supported).

http://www.gradle.org/docs/current/dsl/org.gradle.api.tasks.testing.Test.html

so for your specific configuration you would just do:

```groovy
test {
    include '**/*_Test.class'
    maxHeapSize = '2048m'
    maxParallelForks = 4
    forkEvery = 200
    jvmArgs '-XX:MaxPermSize=512m', '-XX:-UseSplitVerifier'
    ignoreFailures false
}
```

in the build.gradle of the test stub project.

**Comment by mpost** [comment]
Ah okay. Thanks for the info. I'll try to pass out Paramus via test.

**Comment by kageiit** [comment]
@mpost Let me if that works, so I can close this issue!

**Comment by mpost** [comment]
I can confirm that using the test { } directive correctly passes the arguments.
