### ISSUE TITLE
Debug tests in AndroidStudio

### ISSUE THREAD

**Issue by ogranada** [kageiit/gradle-robojava-plugin#8]
Exists any way to run tests via robo-java in debug mode in AndroidStudio?

**Comment by kageiit** [comment]
debugging is fully supported already. just set breakpoints and hit the debug button in studio. Can you be more specific what the problem is?

**Comment by ogranada** [comment]
What is the run configuration to start the debug process?

I go to:
``` Run > Edit Configurations > Add New Configurations (The + button) > Gradle ```
And edit with my project and the task test.

**Comment by ogranada** [comment]
In the new versions of Android Studio the option "Use in-process build" is enabled by default, it should be disabled to run the test in the debugger.
See [this link](http://stackoverflow.com/questions/21184490/how-to-debug-when-running-robolectric-tests-in-android-studio) for more info about how disable it.
