### ISSUE TITLE
Unable to refactor main sources due to stub project.

### ISSUE THREAD

**Issue by LukeStClair** [kageiit/gradle-robojava-plugin#9]
Current approach for tests is messing up refactor/finding code/finding resources.

**Comment by kageiit** [comment]
I have removed the android project main sources from the stub project's sources. This should fix the refactoring/finding layouts etc. in Android studio back to normal.

However, this does mean that debugging is a bit less straightforward. You have to put your break points inside the main source if you want to debug and cannot step in directly from the test class.

**Comment by mpost** [comment]
Thanks for your feedback. Updating to 1.2.2 solves the issue.
